# Generated by Django 5.2.5 on 2025-10-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
    ]
