# Generated by Django 6.0.5 on 2026-05-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedWebsiteAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('window_title', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.employee')),
            ],
        ),
    ]
