# Generated by Django 5.2.5 on 2026-06-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_security_hardening'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
                ('session_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dept', 'session_date'), name='unique_department_session_per_day')],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='department_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_sessions', to='monitoring.departmentsession'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('end_time__isnull', True)), fields=('employee',), name='unique_active_session_per_employee'),
        ),
    ]
