# Generated by Django 6.0.5 on 2026-05-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_blockedwebsiteattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.employee')),
            ],
        ),
    ]
