# Generated by Django 6.0.5 on 2026-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_screenshotlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Idle', 'Idle'), ('Offline', 'Offline')], default='Offline', max_length=20),
        ),
    ]
