# Generated by Django 6.0.5 on 2026-06-05 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_employee_last_seen_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedsite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
