# Generated by Django 5.2.5 on 2026-06-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_merge_department_sessions_and_activity_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshotlog',
            name='metadata_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
