# Generated by Django 5.2.5 on 2026-06-26 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_screenshotlog_metadata_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='department_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_sessions', to='monitoring.departmentsession'),
        ),
    ]
