# Generated by Django 5.2.5 on 2026-07-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_agentheartbeat'),
        ('monitoring', '0010_alter_session_department_session'),
    ]

    operations = [
    ]
