# Generated by Django 5.2.5 on 2026-07-07 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_merge_20260707_1933'),
        ('platform_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentheartbeat',
            name='device_id',
            field=models.CharField(default='dev-xyz', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentheartbeat',
            name='tenant_id',
            field=models.CharField(default='t-1001', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_employees', to='platform_core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='agentheartbeat',
            unique_together={('tenant_id', 'device_id')},
        ),
    ]
